spring:
  profiles:
    include: oauth, cloud

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/funding?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: mysql

  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 500
    open-in-view: false

  data:
    redis:
      port: 6379
      host: localhost

  servlet:
    multipart:
      file-size-threshold: 2MB
      location: /tmp/s3
      max-file-size: 2MB
      max-request-size: 12MB

jwt:
  key: c3ByaW5nLWJvb3QtYXBpLWp3dC1zZWNyZXQta2V5LXN1cGVyLXNlY3JldC15ZXMteWVzLXllcy0yNAo=

scheduler:
  funding-product:
    views: "0 0 0 * * *"

logging:
  level:
    org:
      springframework:
        security: DEBUG